# Generated by Django 5.0.3 on 2026-08-06 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_chat', '0004_queues_block_message_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('widget', 'Widget'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('vk', 'VK'), ('ok', 'OK'), ('api', 'API')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(default='unknown', max_length=32)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('max_queue_size', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DialogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('actor_name', models.CharField(blank=True, default='', max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='operator', max_length=16)),
                ('presence', models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('break', 'Break'), ('training', 'Training'), ('lunch', 'Lunch'), ('meeting', 'Meeting'), ('tech_issue', 'Technical issue'), ('offline', 'Offline')], db_index=True, default='offline', max_length=16)),
                ('max_active_dialogs', models.PositiveIntegerField(default=3)),
                ('auto_assign', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('priority', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='WidgetPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('site_url', models.URLField(blank=True, default='')),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('queue_message', models.TextField(blank=True, default='')),
                ('offline_message', models.TextField(blank=True, default='')),
                ('require_phone', models.BooleanField(default=False)),
                ('form_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='dialogtranscriptemail',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameIndex(
            model_name='dialog',
            new_name='online_chat_status_15cf9b_idx',
            old_name='online_chat_status_6f0d0a_idx',
        ),
        migrations.AddField(
            model_name='dialog',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialog',
            name='last_client_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('rejected', 'Rejected'), ('lost', 'Lost'), ('offline', 'Offline'), ('escalated', 'Escalated')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dialog',
            name='routing_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dialog',
            name='sla_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelconnection',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='online_chat.department'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='online_chat.department'),
        ),
        migrations.AddField(
            model_name='dialogevent',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='online_chat.dialog'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_messages', to='online_chat.dialog'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='operators', to='online_chat.department'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_messages_received', to='online_chat.operatorprofile'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_messages_sent', to='online_chat.operatorprofile'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='online_chat.operatorprofile'),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='online_chat.department'),
        ),
        migrations.AddField(
            model_name='widgetplacement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='online_chat.department'),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='online_chat.widgetplacement'),
        ),
    ]
