# Generated by Django 5.0.3 on 2026-08-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_chat', '0011_assignment_tg_sufler_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operatorassignmenthold',
            new_name='online_chat_operato_adcdae_idx',
            old_name='online_chat_operato_hold_idx',
        ),
    ]
