# Generated by Django 5.0.3 on 2026-07-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsrDialogueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('telephony', 'Телефония'), ('online_chat', 'Онлайн-чат')], max_length=32)),
                ('operator_id', models.CharField(blank=True, max_length=64)),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('min_confidence', models.FloatField(default=0.0)),
                ('recognition_status', models.CharField(choices=[('recognized', 'Распознано'), ('unrecognized', 'Не распознано'), ('partial', 'Частично')], db_index=True, default='partial', max_length=32)),
                ('audio_url', models.CharField(blank=True, max_length=512)),
                ('has_training_candidate', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ASR dialogue session',
                'verbose_name_plural': 'ASR dialogue sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AsrTranscriptUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('operator', 'Оператор'), ('client', 'Клиент')], max_length=32)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(default=0)),
                ('is_unrecognized', models.BooleanField(default=False)),
                ('training_candidate', models.BooleanField(db_index=True, default=False)),
                ('exemplar_candidate', models.BooleanField(default=False)),
                ('annotated_by', models.CharField(blank=True, max_length=150)),
                ('annotated_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='reports.asrdialoguesession')),
            ],
            options={
                'verbose_name': 'ASR transcript utterance',
                'verbose_name_plural': 'ASR transcript utterances',
                'ordering': ('turn_index',),
                'unique_together': {('session', 'turn_index')},
            },
        ),
    ]
