# Generated by Django 5.0.3 on 2026-08-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_asr_qa"),
    ]

    operations = [
        migrations.CreateModel(
            name="CcReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metrics", models.JSONField(default=list)),
                ("view_mode", models.CharField(default="table", max_length=32)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("owner_username", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CC report template",
                "verbose_name_plural": "CC report templates",
                "ordering": ("-updated_at",),
            },
        ),
    ]
