# Generated by Django 6.0.2 on 2026-02-06 07:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('chat', 'Онлайн-чат'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('phone', 'Телефонный звонок')], default='chat', max_length=20, verbose_name='Канал')),
                ('ai_session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание сессии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чатов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (сек)')),
                ('transcription', models.TextField(blank=True, verbose_name='Транскрипция')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_log', to='chat.chatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Лог звонка',
                'verbose_name_plural': 'Логи звонков',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chat.client', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('client', 'Клиент'), ('operator', 'Оператор'), ('ai_recommendation', 'Рекомендация AI'), ('ai_response', 'Ответ AI')], max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('is_transcription', models.BooleanField(default=False, verbose_name='Транскрипция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
    ]
