# Generated by Django 6.0.2 on 2026-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='chat_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='История по каналам'),
        ),
    ]
