"""
Django settings for sufler project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--0vzz%mf6g!%1@$8+(o-kft2$(($ybs+kv$yh0mex4$*abihop",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'audit.apps.AuditConfig',
    'chat',
    'hub.apps.HubConfig',
    'ingest.apps.IngestConfig',
    'qu.apps.QuConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditMiddleware',
    'auth.middleware.RBACMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sufler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'auth.context_processors.rbac',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sufler.wsgi.application'
ASGI_APPLICATION = 'sufler.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "sufler"),
            "USER": os.getenv("POSTGRES_USER", "sufler"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.environ["POSTGRES_HOST"],
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication and I.4 RBAC.
AUTH_MODE = os.getenv(
    "AUTH_MODE",
    "mock_ldap" if DEBUG else "model",
).strip().lower()
AUTH_MOCK_LDAP_USERS_JSON = os.getenv("AUTH_MOCK_LDAP_USERS_JSON", "")
AUTH_MOCK_LDAP_DEFAULT_PASSWORD = os.getenv(
    "AUTH_MOCK_LDAP_DEFAULT_PASSWORD",
    "dev-only-password",
)
AUTH_MOCK_LDAP_ALLOW_INSECURE = os.getenv(
    "AUTH_MOCK_LDAP_ALLOW_INSECURE",
    "false",
).lower() in {"1", "true", "yes"}
AUTH_LDAP_ROLE_GROUP_MAP = {}

if AUTH_MODE == "mock_ldap":
    AUTHENTICATION_BACKENDS = [
        "auth.mock_ldap.MockLDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]
elif AUTH_MODE == "ldap":
    from auth.ldap_config import build_ldap_settings

    globals().update(build_ldap_settings())
    AUTHENTICATION_BACKENDS = [
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]
elif AUTH_MODE == "model":
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
    ]
else:
    raise ImproperlyConfigured(
        "AUTH_MODE must be one of: mock_ldap, ldap, model"
    )

# Path policies are opt-in so legacy routes remain compatible. New Hub/API
# routes should use decorators or add a prefix here.
RBAC_PATH_PERMISSIONS = {}
RBAC_PUBLIC_PATH_PREFIXES = (
    "/api/v1/knowledge/",
    "/client-info/",
    "/static/",
    "/admin/login/",
)

SUZ_WEBHOOK_HMAC_SECRET = os.getenv("SUZ_WEBHOOK_HMAC_SECRET", "")

MODEL_REGISTRY_PATH = Path(
    os.getenv(
        "MODEL_REGISTRY_PATH",
        str(BASE_DIR / "config" / "model_registry.yaml"),
    )
)

# Structured VI.3 audit and KUMA-compatible sinks.
AUDIT_ENABLED = os.getenv("AUDIT_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
}
AUDIT_SINKS = tuple(
    sink.strip().lower()
    for sink in os.getenv("AUDIT_SINKS", "file").split(",")
    if sink.strip()
)
AUDIT_FILE_PATH = Path(
    os.getenv(
        "AUDIT_FILE_PATH",
        str(BASE_DIR / "var" / "audit" / "audit.jsonl"),
    )
)
AUDIT_HTTP_COLLECTOR_URL = os.getenv("AUDIT_HTTP_COLLECTOR_URL", "")
AUDIT_HTTP_TIMEOUT_SECONDS = float(
    os.getenv("AUDIT_HTTP_TIMEOUT_SECONDS", "5")
)
AUDIT_DEVICE_VENDOR = os.getenv("AUDIT_DEVICE_VENDOR", "Belarusbank")
AUDIT_DEVICE_PRODUCT = os.getenv("AUDIT_DEVICE_PRODUCT", "AI_Hub")
AUDIT_DEVICE_VERSION = os.getenv("AUDIT_DEVICE_VERSION", "0.1.0-dev")
AUDIT_SOURCE_SERVICE = os.getenv(
    "AUDIT_SOURCE_SERVICE",
    "sufler-backend",
)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки сессии
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 3600  # 1 час
SESSION_SAVE_EVERY_REQUEST = True

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    CELERY_BROKER_URL,
)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "http://localhost:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ROOT_USER", "")
MINIO_SECRET_KEY = os.getenv("MINIO_ROOT_PASSWORD", "")
