"""
Django settings for sufler project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _running_tests() -> bool:
    joined = " ".join(sys.argv).lower()
    if "pytest" in joined or os.environ.get("PYTEST_CURRENT_TEST"):
        return True
    return any(arg in {"test", "pytest"} for arg in sys.argv[1:2])


def _load_env_files() -> None:
    """Load local .env for runserver/daphne. Skip during unit tests."""
    if _running_tests():
        return
    repo_root = BASE_DIR.parent
    for path in (
        repo_root / "infra" / ".env",
        BASE_DIR / ".env",
        repo_root / ".env",
    ):
        if not path.is_file():
            continue
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip("'").strip('"')
            if key and key not in os.environ:
                os.environ[key] = value


_load_env_files()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--0vzz%mf6g!%1@$8+(o-kft2$(($ybs+kv$yh0mex4$*abihop",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'channels',
    'audit.apps.AuditConfig',
    'chat',
    'hub.apps.HubConfig',
    'ingest.apps.IngestConfig',
    'qu.apps.QuConfig',
    'orchestrator.apps.OrchestratorConfig',
    'assistant.apps.AssistantConfig',
    'ocr.apps.OcrConfig',
    'telephony.apps.TelephonyConfig',
    'reports.apps.ReportsConfig',
    'api_docs.apps.ApiDocsConfig',
    'online_chat.apps.OnlineChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditMiddleware',
    'auth.middleware.RBACMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sufler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'auth.context_processors.rbac',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sufler.wsgi.application'
ASGI_APPLICATION = 'sufler.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
if os.getenv("REDIS_URL") or os.getenv("REDIS_HOST"):
    redis_url = os.getenv("REDIS_URL")
    if not redis_url:
        redis_host = os.getenv("REDIS_HOST", "127.0.0.1")
        redis_port = os.getenv("REDIS_PORT", "6379")
        redis_password = os.getenv("REDIS_PASSWORD", "")
        if redis_password:
            redis_url = f"redis://:{redis_password}@{redis_host}:{redis_port}/0"
        else:
            redis_url = f"redis://{redis_host}:{redis_port}/0"
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [redis_url]},
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "sufler"),
            "USER": os.getenv("POSTGRES_USER", "sufler"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.environ["POSTGRES_HOST"],
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication and I.4 / I.10 RBAC.
# AUTH_BACKEND preferred (ldaps|mock_ldap|model); AUTH_MODE kept as alias (P2-01).
from auth.ldap_config import resolve_auth_backend

AUTH_BACKEND = os.getenv("AUTH_BACKEND", "").strip()
AUTH_MODE = os.getenv(
    "AUTH_MODE",
    "mock_ldap" if DEBUG else "model",
).strip().lower()
AUTH_MODE = resolve_auth_backend(
    auth_backend=AUTH_BACKEND or None,
    auth_mode=AUTH_MODE,
    debug=DEBUG,
)
# Canonical name after normalize (ldaps replaces legacy "ldap").
AUTH_BACKEND = AUTH_MODE
AUTH_MOCK_LDAP_USERS_JSON = os.getenv("AUTH_MOCK_LDAP_USERS_JSON", "")
AUTH_MOCK_LDAP_DEFAULT_PASSWORD = os.getenv(
    "AUTH_MOCK_LDAP_DEFAULT_PASSWORD",
    "dev-only-password",
)
AUTH_MOCK_LDAP_ALLOW_INSECURE = os.getenv(
    "AUTH_MOCK_LDAP_ALLOW_INSECURE",
    "false",
).lower() in {"1", "true", "yes"}
AUTH_LDAP_ROLE_GROUP_MAP = {}

if AUTH_BACKEND == "mock_ldap":
    AUTHENTICATION_BACKENDS = [
        "auth.mock_ldap.MockLDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]
elif AUTH_BACKEND == "ldaps":
    from auth.ldap_config import build_ldap_settings

    globals().update(build_ldap_settings())
    AUTHENTICATION_BACKENDS = [
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]
elif AUTH_BACKEND == "model":
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
    ]
else:
    raise ImproperlyConfigured(
        "AUTH_BACKEND must be one of: ldaps, mock_ldap, model"
    )

# Path policies are opt-in so legacy routes remain compatible. New Hub/API
# routes should use decorators or add a prefix here.
RBAC_PATH_PERMISSIONS = {}
RBAC_PUBLIC_PATH_PREFIXES = (
    "/api/v1/knowledge/",
    "/api/v1/online-chat/",
    "/api/auth/login/",
    "/api/auth/logout/",
    "/api/schema/",
    "/api/docs/",
    "/api/redoc/",
    "/health/",
    "/metrics/",
    "/client-info/",
    "/static/",
    "/admin/login/",
)

SUZ_INGEST_MODE = os.getenv("SUZ_INGEST_MODE", "mock").strip().lower() or "mock"
SUZ_WEBHOOK_HMAC_SECRET = os.getenv("SUZ_WEBHOOK_HMAC_SECRET", "")
SUZ_WEBHOOK_PATH = os.getenv(
    "SUZ_WEBHOOK_PATH",
    "/api/v1/knowledge/events",
)
_suz_iblocks = os.getenv("SUZ_ALLOWED_IBLOCK_IDS", "").strip()
SUZ_ALLOWED_IBLOCK_IDS = frozenset(
    int(part.strip())
    for part in _suz_iblocks.split(",")
    if part.strip().isdigit()
)
# INT-09 Model B polling fallback (Bitrix outbox /changes).
BITRIX_REST_BASE_URL = os.getenv("BITRIX_REST_BASE_URL", "").rstrip("/")
BITRIX_SERVICE_TOKEN = os.getenv("BITRIX_SERVICE_TOKEN", "")
BITRIX_CHANGES_PATH = os.getenv(
    "BITRIX_CHANGES_PATH",
    "/local/api/sufler/v1/changes",
)
BITRIX_HTTP_TIMEOUT_SECONDS = float(
    os.getenv("BITRIX_HTTP_TIMEOUT_SECONDS", "15")
)
SUZ_RECONCILE_ENABLED = os.getenv("SUZ_RECONCILE_ENABLED", "false").lower() in {
    "1",
    "true",
    "yes",
}
SUZ_RECONCILE_LIMIT = int(os.getenv("SUZ_RECONCILE_LIMIT", "100"))
SUZ_RECONCILE_INTERVAL_SECONDS = int(
    os.getenv("SUZ_RECONCILE_INTERVAL_SECONDS", "300")
)

MODEL_REGISTRY_PATH = Path(
    os.getenv(
        "MODEL_REGISTRY_PATH",
        str(BASE_DIR / "config" / "model_registry.yaml"),
    )
)
# Bank TEST inference binding (ModelRegistry deployment_profiles.test).
AI_INFERENCE_PROFILE = os.getenv("AI_INFERENCE_PROFILE", "test").strip() or "test"
# Optional override of slot kpi.gateway_mode (stub|openai).
MODEL_GATEWAY_MODE = os.getenv("MODEL_GATEWAY_MODE", "").strip()
ASR_MODE = os.getenv("ASR_MODE", "stub").strip() or "stub"
ASR_WS_URL = os.getenv("ASR_WS_URL", "ws://asr:8765/")
ASR_HEALTH_URL = os.getenv("ASR_HEALTH_URL", "http://asr:8764/health")

# Structured VI.3 audit and KUMA-compatible sinks (P2-05 schema_version=1.0 unchanged).
AUDIT_ENABLED = os.getenv("AUDIT_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
}
AUDIT_SINKS = tuple(
    sink.strip().lower()
    for sink in os.getenv("AUDIT_SINKS", "file").split(",")
    if sink.strip()
)
AUDIT_FILE_PATH = Path(
    os.getenv(
        "AUDIT_FILE_PATH",
        str(BASE_DIR / "var" / "audit" / "audit.jsonl"),
    )
)
# Prefer AUDIT_KUMA_COLLECTOR_URL (VI.3 prod); fall back to AUDIT_HTTP_COLLECTOR_URL.
AUDIT_HTTP_COLLECTOR_URL = (
    os.getenv("AUDIT_KUMA_COLLECTOR_URL", "").strip()
    or os.getenv("AUDIT_HTTP_COLLECTOR_URL", "").strip()
)
AUDIT_KUMA_COLLECTOR_URL = AUDIT_HTTP_COLLECTOR_URL
AUDIT_HTTP_TIMEOUT_SECONDS = float(
    os.getenv("AUDIT_HTTP_TIMEOUT_SECONDS", "5")
)
AUDIT_DEVICE_VENDOR = os.getenv("AUDIT_DEVICE_VENDOR", "Belarusbank")
AUDIT_DEVICE_PRODUCT = os.getenv("AUDIT_DEVICE_PRODUCT", "AI_Hub")
AUDIT_DEVICE_VERSION = os.getenv("AUDIT_DEVICE_VERSION", "0.1.0-dev")
AUDIT_SOURCE_SERVICE = os.getenv(
    "AUDIT_SOURCE_SERVICE",
    "sufler-backend",
)

# VI.2 Oktell telephony adapter (P4-02).
# OKTELL_MODE=mock → local oktell_mock; prod → TEST line T+45 / real WS.
OKTELL_MODE = os.getenv("OKTELL_MODE", "mock").strip().lower() or "mock"
OKTELL_ENABLED = os.getenv("OKTELL_ENABLED", "false").lower() in {
    "1",
    "true",
    "yes",
}
OKTELL_WS_URL = os.getenv("OKTELL_WS_URL", "ws://127.0.0.1:8766")
OKTELL_MOCK_WS_URL = os.getenv("OKTELL_MOCK_WS_URL", "ws://127.0.0.1:8766")
OKTELL_PROD_WS_URL = os.getenv("OKTELL_PROD_WS_URL", "")
OKTELL_SUBSCRIBE_EVENT = os.getenv("OKTELL_SUBSCRIBE_EVENT", "phoneevent")
OKTELL_OPEN_TIMEOUT_SECONDS = float(
    os.getenv("OKTELL_OPEN_TIMEOUT_SECONDS", "5")
)
OKTELL_PROFILE_ID = os.getenv("OKTELL_PROFILE_ID", "test_line_t45")
OKTELL_TEST_LINE_LABEL = os.getenv(
    "OKTELL_TEST_LINE_LABEL",
    "T+45 test line",
)
OKTELL_TEST_QUEUE = os.getenv("OKTELL_TEST_QUEUE", "")
OKTELL_TEST_MARKING = os.getenv("OKTELL_TEST_MARKING", "TEST_OKTELL_T45")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Online-chat transcript e-mail (§4.4.28).
# Local default: file backend → letters as .log/.eml under EMAIL_FILE_PATH (always works).
# Docker compose: SMTP → Mailpit (UI http://localhost:8025).
# Prod: bank SMTP relay + ONLINE_CHAT_FROM_EMAIL from ДРиРИТ.
_email_backend_default = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", _email_backend_default)
EMAIL_FILE_PATH = Path(
    os.getenv(
        "EMAIL_FILE_PATH",
        str(BASE_DIR / "var" / "mail"),
    )
)
try:
    EMAIL_FILE_PATH.mkdir(parents=True, exist_ok=True)
except OSError:
    pass
EMAIL_HOST = os.getenv("EMAIL_HOST", "127.0.0.1")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "1025"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() in {"1", "true", "yes"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in {"1", "true", "yes"}
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "online-chat@belarusbank.by",
)
ONLINE_CHAT_FROM_EMAIL = os.getenv("ONLINE_CHAT_FROM_EMAIL", DEFAULT_FROM_EMAIL)
ONLINE_CHAT_TRANSCRIPT_SUBJECT = os.getenv(
    "ONLINE_CHAT_TRANSCRIPT_SUBJECT",
    "Беларусбанк: переписка с онлайн-консультантом",
)

# Настройки сессии
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 3600  # 1 час
SESSION_SAVE_EVERY_REQUEST = True

# SPA on Vite (:5173) posts with Origin: http://127.0.0.1:5173 while the API
# is proxied to Django. Without trusted origins Django rejects CSRF even when
# X-CSRFToken matches the cookie (browser always sends Origin on POST).
_CSRF_TRUSTED_DEFAULT = (
    "http://127.0.0.1:5173,"
    "http://localhost:5173,"
    "http://127.0.0.1:8001,"
    "http://localhost:8001,"
    "http://127.0.0.1:8000,"
    "http://localhost:8000"
)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        _CSRF_TRUSTED_DEFAULT,
    ).split(",")
    if origin.strip()
]
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    CELERY_BROKER_URL,
)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "http://localhost:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ROOT_USER", "")
MINIO_SECRET_KEY = os.getenv("MINIO_ROOT_PASSWORD", "")
MINIO_OCR_BUCKET = os.getenv("MINIO_OCR_BUCKET", "sufler-ocr")
MINIO_ONLINE_CHAT_BUCKET = os.getenv(
    "MINIO_ONLINE_CHAT_BUCKET",
    "sufler-online-chat",
)
# auto | fs | minio — fs used when credentials empty or tests override.
OCR_OBJECT_STORE_BACKEND = os.getenv("OCR_OBJECT_STORE_BACKEND", "auto")
OCR_OBJECT_STORE_ROOT = Path(
    os.getenv(
        "OCR_OBJECT_STORE_ROOT",
        str(BASE_DIR / "var" / "ocr-objects"),
    )
)
OCR_MAX_UPLOAD_BYTES = int(os.getenv("OCR_MAX_UPLOAD_BYTES", str(25 * 1024 * 1024)))

# Online-chat external seams. Local runs use filesystem storage and disabled
# channel delivery; production only needs credentials/endpoints supplied via env.
ONLINE_CHAT_OBJECT_STORE_BACKEND = os.getenv(
    "ONLINE_CHAT_OBJECT_STORE_BACKEND",
    "auto",
)
ONLINE_CHAT_OBJECT_STORE_ROOT = Path(
    os.getenv(
        "ONLINE_CHAT_OBJECT_STORE_ROOT",
        str(BASE_DIR / "var" / "online-chat-objects"),
    )
)
ONLINE_CHAT_MAX_UPLOAD_BYTES = int(
    os.getenv("ONLINE_CHAT_MAX_UPLOAD_BYTES", str(10 * 1024 * 1024))
)
ONLINE_CHAT_ALLOWED_UPLOAD_TYPES = tuple(
    item.strip()
    for item in os.getenv(
        "ONLINE_CHAT_ALLOWED_UPLOAD_TYPES",
        "image/jpeg,image/png,application/pdf,text/plain",
    ).split(",")
    if item.strip()
)
ONLINE_CHAT_CHANNEL_HTTP_TIMEOUT_SECONDS = float(
    os.getenv("ONLINE_CHAT_CHANNEL_HTTP_TIMEOUT_SECONDS", "10")
)
ONLINE_CHAT_LOST_TIMEOUT_SECONDS = int(
    os.getenv("ONLINE_CHAT_LOST_TIMEOUT_SECONDS", "600")
)
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_WEBHOOK_SECRET = os.getenv("TELEGRAM_WEBHOOK_SECRET", "")
# polling | webhook | both — test contour defaults to long poll (no HTTPS/ngrok).
TELEGRAM_MODE = (os.getenv("TELEGRAM_MODE", "polling") or "polling").strip().lower()
TELEGRAM_POLL_TIMEOUT_SECONDS = int(os.getenv("TELEGRAM_POLL_TIMEOUT_SECONDS", "25"))
VIBER_AUTH_TOKEN = os.getenv("VIBER_AUTH_TOKEN", "")
VK_ACCESS_TOKEN = os.getenv("VK_ACCESS_TOKEN", "")
VK_WEBHOOK_SECRET = os.getenv("VK_WEBHOOK_SECRET", "")
VK_CONFIRMATION_CODE = os.getenv("VK_CONFIRMATION_CODE", "")
OK_ACCESS_TOKEN = os.getenv("OK_ACCESS_TOKEN", "")
OK_WEBHOOK_SECRET = os.getenv("OK_WEBHOOK_SECRET", "")
ONLINE_CHAT_API_CHANNEL_SIGNING_SECRET = os.getenv(
    "ONLINE_CHAT_API_CHANNEL_SIGNING_SECRET",
    "",
)
CELERY_BEAT_SCHEDULE = {
    "online-chat-classify-stale-dialogs": {
        "task": "online_chat.tasks.classify_stale_dialogs",
        "schedule": 60.0,
    },
    # Drives the automatic online/offline transition by date/time in prod —
    # no manual "start/stop work day" button needed outside the test simulator.
    "online-chat-sync-work-schedule": {
        "task": "online_chat.tasks.sync_work_schedule",
        "schedule": 20.0,
    },
}

# Original assistant KB uploads (for source download from chat citations).
ASSISTANT_KB_STORAGE_ROOT = Path(
    os.getenv(
        "ASSISTANT_KB_STORAGE_ROOT",
        str(BASE_DIR / "var" / "assistant-kb"),
    )
)

# Django REST Framework + drf-spectacular (OpenAPI `/api/schema/`).
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Sufler AI Hub API",
    "DESCRIPTION": (
        "OpenAPI for integrators and приёмка. Curated paths for "
        "assistant, sufler, and ingest are merged via postprocessing hook."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "POSTPROCESSING_HOOKS": [
        "api_docs.openapi_v1.merge_into_spectacular_schema",
    ],
}
