from django.urls import path

from online_chat.views import (
    ad_pending_operators,
    analytics,
    assignment_settings,
    base_message_detail,
    base_messages_collection,
    bot_detail,
    bots_collection,
    channel_detail,
    channel_health_check,
    channels_collection,
    client_block_lift,
    client_blocks_collection,
    client_history,
    dialog_accept,
    dialog_attachment_download,
    dialog_attachment_upload,
    dialog_block,
    dialog_close,
    dialog_detail,
    dialog_feedback,
    dialog_mark_read,
    dialog_message_detail,
    dialog_messages,
    dialog_presence,
    dialog_send_transcript,
    dialog_transfer,
    dialogs_collection,
    department_detail,
    departments_collection,
    dev_reset,
    dev_seed,
    internal_messages_collection,
    internal_messages_mark_read,
    operator_detail,
    operator_photo,
    operator_presence,
    operators_collection,
    placement_detail,
    placements_collection,
    routing_rule_detail,
    routing_rules_collection,
    routing_run,
    sla_settings,
    sufler_hint_feedback,
    sufler_outage_report,
    supervisor_overview,
    widget_config,
    work_day_control,
    work_schedule_settings,
    work_schedule_status,
)

urlpatterns = [
    path("departments/", departments_collection, name="online_chat_departments"),
    path("departments/<uuid:item_id>/", department_detail, name="online_chat_department"),
    path("operators/", operators_collection, name="online_chat_operators"),
    path(
        "operators/<uuid:item_id>/photo/",
        operator_photo,
        name="online_chat_operator_photo",
    ),
    path("operators/<uuid:item_id>/", operator_detail, name="online_chat_operator"),
    path(
        "operators/<uuid:item_id>/presence/",
        operator_presence,
        name="online_chat_operator_presence",
    ),
    path("placements/", placements_collection, name="online_chat_placements"),
    path("placements/<uuid:item_id>/", placement_detail, name="online_chat_placement"),
    path("channels/", channels_collection, name="online_chat_channels"),
    path("channels/<uuid:item_id>/", channel_detail, name="online_chat_channel"),
    path(
        "channels/<uuid:item_id>/health/",
        channel_health_check,
        name="online_chat_channel_health",
    ),
    path("routing-rules/", routing_rules_collection, name="online_chat_routing_rules"),
    path("bots/", bots_collection, name="online_chat_bots"),
    path("bots/<uuid:item_id>/", bot_detail, name="online_chat_bot"),
    path("base-messages/", base_messages_collection, name="online_chat_base_messages"),
    path(
        "base-messages/<uuid:item_id>/",
        base_message_detail,
        name="online_chat_base_message",
    ),
    path(
        "routing-rules/<uuid:item_id>/",
        routing_rule_detail,
        name="online_chat_routing_rule",
    ),
    path("supervisor/overview/", supervisor_overview, name="online_chat_supervisor"),
    path("ad/pending-operators/", ad_pending_operators, name="online_chat_ad_pending"),
    path("assignment-settings/", assignment_settings, name="online_chat_assignment_settings"),
    path("sla-settings/", sla_settings, name="online_chat_sla_settings"),
    path("work-schedule/", work_schedule_settings, name="online_chat_work_schedule"),
    path(
        "work-schedule/status/",
        work_schedule_status,
        name="online_chat_work_schedule_status",
    ),
    path("work-schedule/control/", work_day_control, name="online_chat_work_day_control"),
    path("sufler-feedback/", sufler_hint_feedback, name="online_chat_sufler_feedback"),
    path("sufler-outage/", sufler_outage_report, name="online_chat_sufler_outage"),
    path("analytics/", analytics, name="online_chat_analytics"),
    path("history/", client_history, name="online_chat_client_history"),
    path(
        "internal-messages/",
        internal_messages_collection,
        name="online_chat_internal_messages",
    ),
    path(
        "internal-messages/read/",
        internal_messages_mark_read,
        name="online_chat_internal_messages_read",
    ),
    path("routing/run/", routing_run, name="online_chat_routing_run"),
    path("dev/seed/", dev_seed, name="online_chat_dev_seed"),
    path("dev/reset/", dev_reset, name="online_chat_dev_reset"),
    path("config/widget/<str:widget_id>/", widget_config, name="online_chat_widget_config"),
    path("dialogs/", dialogs_collection, name="online_chat_dialogs"),
    path("dialogs/<uuid:dialog_id>/", dialog_detail, name="online_chat_dialog"),
    path(
        "dialogs/<uuid:dialog_id>/messages/",
        dialog_messages,
        name="online_chat_dialog_messages",
    ),
    path(
        "dialogs/<uuid:dialog_id>/attachments/",
        dialog_attachment_upload,
        name="online_chat_dialog_attachment_upload",
    ),
    path(
        "dialogs/<uuid:dialog_id>/attachments/<uuid:message_id>/",
        dialog_attachment_download,
        name="online_chat_dialog_attachment_download",
    ),
    path(
        "dialogs/<uuid:dialog_id>/messages/<uuid:message_id>/",
        dialog_message_detail,
        name="online_chat_dialog_message",
    ),
    path(
        "dialogs/<uuid:dialog_id>/accept/",
        dialog_accept,
        name="online_chat_dialog_accept",
    ),
    path(
        "dialogs/<uuid:dialog_id>/transfer/",
        dialog_transfer,
        name="online_chat_dialog_transfer",
    ),
    path(
        "dialogs/<uuid:dialog_id>/close/",
        dialog_close,
        name="online_chat_dialog_close",
    ),
    path(
        "dialogs/<uuid:dialog_id>/block/",
        dialog_block,
        name="online_chat_dialog_block",
    ),
    path(
        "dialogs/<uuid:dialog_id>/read/",
        dialog_mark_read,
        name="online_chat_dialog_read",
    ),
    path(
        "dialogs/<uuid:dialog_id>/presence/",
        dialog_presence,
        name="online_chat_dialog_presence",
    ),
    path(
        "dialogs/<uuid:dialog_id>/feedback/",
        dialog_feedback,
        name="online_chat_dialog_feedback",
    ),
    path(
        "dialogs/<uuid:dialog_id>/send-transcript/",
        dialog_send_transcript,
        name="online_chat_dialog_send_transcript",
    ),
    path("blocks/", client_blocks_collection, name="online_chat_blocks"),
    path(
        "blocks/<uuid:block_id>/lift/",
        client_block_lift,
        name="online_chat_block_lift",
    ),
]
