# Generated by Django 5.0.3 on 2026-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_kb_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('deep_link', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(default='tool', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assistant capabilities',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AssistantKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('scope', models.CharField(default='department', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('ready', 'Ready'), ('error', 'Error')], db_index=True, default='idle', max_length=16)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssistantPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt_type', models.CharField(choices=[('system', 'System'), ('task', 'Task'), ('scope', 'Scope')], db_index=True, default='task', max_length=16)),
                ('scope', models.CharField(default='bank', max_length=64)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kb_slug', models.SlugField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('prompt_type', 'name'),
            },
        ),
    ]
