"""Business-friendly Russian for column «Реализация» (minimal English loanwords)."""

from __future__ import annotations

import re

# Full-text replacements (longest first) after field localization.
_POLISH: list[tuple[str, str]] = [
    ("дымовой тест административного интерфейса", "admin smoke"),
    ("модульный дымовой тест", "модульный smoke"),
    ("дымовой тест", "smoke"),
    ("ASS-T: smoke", "ASS-T smoke"),
    ("DOC-T smoke", "DOC-T smoke"),
    ("CHAT-T smoke", "CHAT-T smoke"),
    ("≥50 `sufler_cc` scenarios in production catalog", "не менее 50 диалоговых сценариев суфлёра загружены в рабочий каталог и опубликованы"),
    ("scenario library ready", "библиотека сценариев готова к работе операторов"),
    ("go-live КЦ", "ввод модуля Контакт-центра в промышленную эксплуатацию"),
    ("channel breakdown", "запрос отчёта с разбивкой по каналам обслуживания"),
    ("tel vs chat metrics", "сбор показателей телефонии и онлайн-чата: объём, качество, использование подсказок"),
    ("channel dashboard", "сводная панель по каналам; выгрузка в Excel/PDF"),
    ("round-robin / load-based", "распределение по очереди или по загрузке оператора"),
    ("round-robin/load assign; cap per operator", "назначение по очереди или по загрузке; лимит диалогов на оператора"),
    ("движок очередей", "механизм очередей: распределяет диалоги между операторами по настроенным правилам"),
    ("dropdown тематики", "выпадающего списка тематики обращения"),
    ("post-chat опрос", "опрос клиента после завершения диалога"),
    ("PostgreSQL + cold archive", "сохранение в базе диалогов и архивная копия в долгосрочном хранилище"),
    ("closed dialog + post-chat", "диалог закрыт; клиенту показывается опрос после обращения"),
    ("operator «Закрыть»", "оператор нажимает «Закрыть»"),
    ("new dialog in queue", "новый диалог клиента в очереди отдела"),
    ("pipeline monitor all QU/RAG/LLM stages", "мониторинг этапов обработки запросов: понимание → поиск → ответ"),
    ("ops dashboard", "операционная панель для аналитика"),
    ("real-time SSE: active dialogs, queues, SLA", "обновление показателей в реальном времени: активные диалоги, очереди, SLA"),
    ("live panel", "оперативная панель"),
    ("FeedbackEvent stream", "поток событий обратной связи от операторов"),
    ("aggregate by role tel/chat", "группировка по роли: телефония / онлайн-чат"),
    ("rel/usefulness report", "отчёт о релевантности и полезности подсказок"),
    ("operator scorecard", "оценка работы оператора по показателям"),
    ("group by operator_id", "группировка по оператору"),
    ("report builder", "конструктор отчёта"),
    ("tables/charts export", "таблицы и графики с выгрузкой"),
    ("scheduled job", "запланированное формирование отчёта"),
    ("report artifact", "готовый файл отчёта"),
    ("filter channel/period/topic", "фильтр по каналу, периоду и тематике"),
    ("saved templates", "сохранённые шаблоны отчётов"),
    ("ASR quality report", "отчёт о качестве распознавания речи"),
    ("separate from client", "без участия клиента"),
    ("internal chat panel", "панель внутренней переписки операторов"),
    ("operator-to-operator msg", "сообщение одного оператора другому"),
    ("read-only stream", "просмотр в режиме только чтения"),
    ("Drag/assign", "перетаскивание / назначение"),
    ("skill-группы", "группы навыков"),
    ("CRUD отделов", "создание, изменение и удаление отделов"),
    ("offline-очередь", "очередь сообщений при отключении клиента"),
    ("reconnect", "повторном подключении"),
    ("POST `/chat/session`", "создание сессии чата"),
    ("summary в АРМ", "краткое резюме предыдущих обращений в рабочем месте оператора"),
    ("push/очередь", "уведомление и очередь"),
    ("assignee", "назначенного оператора"),
    ("JS-snippet + preview", "код для встраивания виджета и предпросмотр"),
    ("REST/webhook", "интеграция через REST или webhook"),
    ("дашборд", "панель мониторинга"),
    ("Dashboard", "панель мониторинга"),
    ("dashboard", "панель мониторинга"),
    ("metrics", "показатели"),
    ("metric", "показатель"),
    ("feedback", "обратная связь"),
    ("timeout", "таймаут"),
    ("online", "в статусе «в сети»"),
    ("offline", "офлайн"),
    ("embed", "встраивание"),
    ("preview", "предпросмотр"),
    ("отдельный thread", "отдельный канал внутренних сообщений"),
    ("intent", "намерение запроса"),
    ("branch", "ветка сценария"),
    ("chips", "кнопки-варианты"),
    ("handoff", "передача оператору"),
    ("sandbox", "тестовой среде"),
    ("semver", "версионирование"),
    ("changelog", "журнал изменений"),
    ("rollback", "откат версии"),
    ("migrate between envs", "перенос между тестовой и промышленной средой"),
    ("published scenario version", "опубликованная версия сценария"),
    ("live update", "обновление без остановки сервиса"),
    ("drag-drop scenario", "редактор сценария с перетаскиванием блоков"),
    ("preview dialog", "предпросмотр диалога по сценарию"),
    ("JSON scenario bundle", "файл сценария в формате JSON"),
    ("blue/green publish without downtime", "публикация новой версии без простоя (blue/green)"),
    ("Studio: branches, API hooks, no code", "редактор Studio: ветвления и вызовы API без программирования"),
    ("author edits graph", "автор редактирует схему сценария"),
    ("hotfix scenario", "срочное исправление сценария"),
    ("admin Studio", "администратор в редакторе Studio"),
    ("admin test", "тестовый прогон администратором"),
    ("version publish", "публикация новой версии"),
    ("import/export", "импорт и экспорт"),
    ("low relevance stats", "статистика низкой релевантности ответов"),
    ("analytics on scenario paths", "анализ путей прохождения сценария"),
    ("scenario per channel", "отдельный сценарий для каждого канала"),
    ("scenario end", "завершение сценария"),
    ("low confidence", "низкая уверенность в ответе"),
    ("channel telephony/chat", "каналы телефония и онлайн-чат"),
    ("same engine, channel-specific entry", "единый движок сценариев с разными точками входа по каналам"),
    ("Hub module load", "открытие модуля в Hub"),
    ("reuse platform LLM service", "использование общего сервиса языковой модели платформы"),
    ("assistant uses shared LLM", "ассистент работает на общей модели банка"),
    ("user query", "запрос пользователя"),
    ("any query", "любой запрос пользователя"),
    ("timely answer", "ответ в установленный срок (SLA)"),
    ("adapted tone", "тон ответов, адаптированный под подразделение"),
    ("terminology / history", "терминология и история обращений подразделения"),
    ("paraphrase query", "перефразированный запрос"),
    ("duplicate question", "повторяющийся вопрос"),
    ("reject duplicate", "отклонение дубликата"),
    ("throughput", "требование к скорости обработки"),
    ("performance SLA", "целевой уровень производительности (SLA)"),
    ("met SLA on load test", "целевые показатели достигнуты при нагрузочном тесте"),
    ("shared LLM layer", "общий слой языковой модели"),
    ("OCR module", "модуль распознавания документов"),
    ("platform LLM for post-OCR tasks", "общая языковая модель для обработки результатов OCR"),
    ("client msg without permalink", "сообщение клиенту без ссылки на СУЗ"),
    ("manual reply", "ручной ответ оператора"),
    ("graceful degradation flag", "переход в режим ручной работы при сбое"),
    ("client message webhook", "входящее сообщение клиента через интеграцию"),
    ("block client action", "действие «заблокировать клиента»"),
    ("client blocked", "клиент заблокирован"),
    ("client disconnect", "клиент отключился"),
    ("supervisor role", "роль супервизора"),
    ("supervisor canvas", "экран супервизора"),
    ("observe + reassign dialogs", "просмотр и переназначение диалогов"),
    ("operator ARM login", "вход оператора в рабочее место (АРМ)"),
    ("authenticated session", "авторизованная сессия"),
    ("secure widget", "защищённый виджет на сайте"),
    ("widget embed", "встраивание виджета"),
    ("admin embed config", "настройка встраивания виджета администратором"),
    ("operator login AD", "вход оператора через учётную запись банка (AD)"),
    ("unified operator desktop", "единое рабочее место оператора"),
    ("pending messages", "со сообщениями, ожидающими доставки"),
    ("routing tables", "таблицы маршрутизации"),
    ("channel adapters → unified store", "адаптеры каналов сохраняют переписку в едином хранилище"),
    ("same ARM for all channels", "одно рабочее место для всех каналов"),
    ("typing indicator / draft bubble", "индикатор набора текста и черновик сообщения"),
    ("operator status change", "смена статуса оператора"),
    ("online/lunch/offline → routing eligibility", "«в сети» / «обед» / «не в сети» влияет на получение новых диалогов"),
    ("status in header", "статус отображается в шапке АРМ"),
    ("admin form builder", "конструктор полей формы входа"),
    ("configurable intake fields", "настраиваемые поля при начале диалога"),
    ("widget form fields", "поля формы в виджете"),
    ("queue wait", "ожидание в очереди"),
    ("custom queue status text", "настраиваемый текст статуса очереди для клиента"),
    ("widget status message", "сообщение о статусе в виджете"),
    ("timeout/offline/reject", "таймаут, офлайн или отказ"),
    ("classify lost/refused/offline", "классификация: потерянный / отклонённый / офлайн"),
    ("status labels + reports", "метки статуса и отчёты"),
    ("bot scenario", "сценарий бота"),
    ("first-line bot → escalate human", "бот первой линии с передачей оператору"),
    ("UC-O7 flow", "сценарий UC-O7"),
    ("negative", "негативный сценарий"),
    ("negative)", "негативный сценарий)"),
    (" negative.", " негативный сценарий."),
    ("admin smoke", "admin smoke"),
    (" smoke", " smoke"),
]


def polish_business(text: str) -> str:
    out = text.strip()
    out = out.replace("embedding", "\x00EMB\x00")
    for old, new in _POLISH:
        if old in out:
            out = out.replace(old, new)
    return out.replace("\x00EMB\x00", "embedding")
