"""Russian localization and expansion for column «Реализация»."""

from __future__ import annotations

import re

# Longest phrases first (applied sequentially).
_PHRASES: list[tuple[str, str]] = [
    # --- FR-UND / QU patterns ---
    (
        "match без exact keyword",
        "семантическое совпадение с документом KB без обязательного совпадения по точному ключевому слову",
    ),
    (
        "embedding similarity; одного примера достаточно",
        "сравнение запроса с эталоном по косинусной близости векторных представлений (embedding); "
        "для синонимов и перефразировок достаточно одного примера в обучающей выборке",
    ),
    ("unit QU", "модульные тесты модуля понимания запросов (QU)"),
    ("unit + ASS-T", "модульные тесты QU и ASS-T"),
    (
        "unsupervised / auto-label; без keyword tagging",
        "обучение без учителя с автоматической разметкой; без ручной разметки ключевых слов",
    ),
    (
        "auto-append Q&A pairs из диалогов в training set KB",
        "автоматическое дополнение пар «вопрос–ответ» из диалогов в обучающую выборку KB",
    ),
    ("hash/similarity gate → reject", "проверка хеша и семантического сходства → отклонение дубликата"),
    ("preview search UI", "интерфейс предпросмотра результатов поиска"),
    ("moderation queue + comment", "очередь модерации с полем комментария администратора"),
    ("approve/reject админом", "утверждение или отклонение администратором"),
    ("escalate to operator channel", "эскалация в канал оператора"),
    ("trigger retrain job post-index", "запуск задачи переобучения после переиндексации"),
    ("queue manual validation", "постановка в очередь ручной валидации"),
    ("auto-add или queue manual validation", "автодобавление или постановка на ручную валидацию"),
    ("ETL FAQ/examples → training store", "ETL: импорт FAQ и примеров из СУЗ в хранилище обучающей выборки"),
    ("semantic rank + score % в результатах", "семантическое ранжирование с показателем релевантности (%) в результатах"),
    ("dual-language models QU", "двуязычные модели модуля понимания запросов (RU/EN)"),
    ("intent на обоих языках", "распознанное намерение на обоих языках"),
    ("deploy on-prem; no external API", "развёртывание on-prem; без обращения к внешним API"),
    ("inference в контуре банка", "вывод модели (inference) в контуре банка"),
    ("versioned training log + rollback", "версионируемый журнал обучения с возможностью отката выборки"),
    # --- FR-CC / infra ---
    ("INT-T network scan", "INT-T: проверка сетевой изоляции"),
    ("SUF-T negative", "SUF-T: негативный сценарий"),
    ("ASS-T-23 / SUF-T negative", "ASS-T-23 / SUF-T: негативный сценарий"),
    (
        "orchestration: QU → RAG `cc_production` → on-prem LLM (`sufler_cc`)",
        "оркестрация: модуль понимания запросов → RAG по индексу `cc_production` → on-prem LLM (промпт `sufler_cc`)",
    ),
    (
        "system prompt + content filter; RAG только `cc_production`",
        "системный промпт и фильтр контента; поиск только по индексу `cc_production`",
    ),
    ("lang detect", "определение языка запроса"),
    (
        "UI CRUD KB суфлёра §4.5.1; upload → chunk → index без кода",
        "интерфейс CRUD баз знаний суфлёра §4.5.1: загрузка → разбиение на фрагменты → индексация без программирования",
    ),
    (
        "multi-tenant embed: site/М-банк/ИБ; отдельный `widget_id` на точку",
        "многоточечное встраивание (multi-tenant): сайт / М-банк / ИБ; отдельный `widget_id` на каждую точку размещения",
    ),
    ("JS-snippet + preview", "JS-фрагмент для встраивания и предпросмотр"),
    (
        "CI/CD патчи Hub; changelog; regression SUF-T/CHAT-T",
        "CI/CD: патчи Hub, журнал изменений, регрессионное тестирование SUF-T / CHAT-T",
    ),
    (
        "horizontal scale ASR/RAG/LLM; PostgreSQL + cold archive",
        "горизонтальное масштабирование ASR / RAG / LLM; PostgreSQL и холодное архивирование",
    ),
    ("load test II.7.4", "нагрузочное тестирование по II.7.4"),
    (
        "pipeline ingest (.pdf, docx, …) → vector index per KB",
        "конвейер загрузки (.pdf, docx, …) → векторный индекс для каждой KB",
    ),
    (
        "metadata `suz_permalink`; channel policy скрывает URL для клиента (чат)",
        "метаданные `suz_permalink`; политика канала скрывает URL СУЗ для клиента (чат)",
    ),
    ("CHAT-T / SUF-T smoke", "CHAT-T / SUF-T smoke"),
    ("load test assistant", "нагрузочное тестирование ассистента"),
    ("load test platform", "нагрузочное тестирование платформы"),
    ("load test OCR", "нагрузочное тестирование OCR"),
    # --- ASR ---
    (
        "streaming ASR RU/EN on-prem",
        "потоковое распознавание речи RU/EN on-prem",
    ),
    ("partial/final transcript → QU", "промежуточный и финальный транскрипт → модуль QU"),
    ("acoustic + LM models bank domain", "акустическая и языковая модели с банковским словарём"),
    ("WER test ≥90%", "тест WER (word error rate) ≥90%"),
    ("70+ concurrent calls", "≥70 одновременных звонков"),
    ("cluster ASR workers; load test", "кластер воркеров ASR; нагрузочное тестирование"),
    ("accuracy ≥90% under noise", "точность ≥90% при шуме и нагрузке"),
    ("streaming pipeline latency ≤1s", "конвейер потокового распознавания с задержкой ≤1 с"),
    ("real-time text to sufer", "текст в реальном времени в панель суфлёра"),
    ("store transcripts 1y; TTL purge", "хранение транскриптов 1 год; автоматическое удаление по TTL"),
    ("dual-leg / noisy channel", "двухканальная запись / канал с повышенным уровнем шума"),
    (
        "noise suppression, AEC, AGC",
        "подавление шума, эхоподавление (AEC), автоматическая регулировка усиления (AGC)",
    ),
    ("cleaner client leg", "очищенная дорожка клиента"),
    ("telephony-tuned acoustic model", "акустическая модель, настроенная под телефонный канал"),
    ("optimized phone ASR", "распознавание, оптимизированное для телефонии"),
    ("auto-punctuation post-processor", "постобработка с автоматической расстановкой пунктуации"),
    ("punctuated transcript", "транскрипт с пунктуацией"),
    (
        "custom dict upload .txt/.xlsx + manual edit",
        "загрузка пользовательского словаря (.txt, .xlsx) и ручное редактирование",
    ),
    ("hotword boost", "повышение веса словарных статей (hotword boost)"),
    ("review low-confidence", "разбор записей с низкой уверенностью распознавания"),
    (
        "speaker diarization operator vs client",
        "диаризация: разделение речи оператора и клиента",
    ),
    ("labeled lines to LLM", "помеченные реплики для LLM"),
    ("streaming ASR from PBX", "потоковое ASR из АТС"),
    (
        "pass call_id, direction, duration to QU metadata",
        "передача call_id, направления и длительности в метаданные QU",
    ),
    ("enriched session context", "обогащённый контекст сессии"),
    ("audit trail", "журнал аудита событий"),
    ("confidence thresholds in Hub UI", "настройка порогов уверенности в интерфейсе Hub"),
    ("tuning without deploy", "настройка без переразвёртывания"),
    ("export as training candidates", "экспорт как кандидатов для дообучения"),
    ("CSV for retrain", "CSV для переобучения"),
    ("ASR autoscale; K8s HPA", "автомасштабирование ASR; HPA в Kubernetes"),
    ("no degradation p95", "без деградации p95"),
    # --- SUF ---
    ("RAG API `cc_production` only; no Bitrix HTTP", "RAG API только `cc_production`; без HTTP к Bitrix в runtime"),
    ("sort DESC by score; invalidate on intent change", "сортировка по убыванию score; сброс при смене намерения"),
    ("≤2 cards ranked", "≤2 ранжированных карточки"),
    ("dual-leg ASR from connect; diarization (открыто INT-T)", "двухканальное ASR с момента соединения; диаризация (открыто INT-T)"),
    ("transcript stream", "поток транскрипта"),
    ("async RAG+LLM; p95 ≤2s @75 ops", "асинхронный RAG+LLM; p95 ≤2 с при 75 операторах"),
    ("карточка ≤2s", "карточка подсказки за ≤2 с"),
    ("graceful degradation flag", "флаг плавной деградации (переход на ручной режим)"),
    (
        "event `asr.final`; debounce 300ms; bind to transcript line",
        "событие `asr.final`; подавление дублей 300 мс; привязка к строке транскрипта",
    ),
    ("lang detect ≥99%; triple block for EN queries", "определение языка ≥99%; тройной блок для EN-запросов"),
    ("history fetch + summary inject prompt", "загрузка истории и вставка summary в промпт"),
    ("QU threshold miss", "порог QU не достигнут"),
    # --- CHAT / UC ---
    ("mandatory topic dropdown (not intake form)", "обязательный выбор тематики из выпадающего списка (не на форме входа)"),
    ("blocklist + audit log", "чёрный список и журнал аудита"),
    ("RBAC read-only peer dialogs", "RBAC: только чтение диалогов коллег"),
    ("view without compose", "просмотр без поля ввода"),
    ("read-only", "только чтение"),
    ("offline queue", "очередь офлайн-сообщений"),
    ("round-robin/load assign", "round-robin / назначение по нагрузке"),
    ("skill groups", "группы навыков (skill groups)"),
    ("typing indicator / draft bubble", "индикатор набора текста / черновик сообщения"),
    ("real-time SSE", "потоковая доставка метрик (SSE) в реальном времени"),
    ("graceful degradation", "плавная деградация сервиса"),
    ("strip URL СУЗ", "удаление URL СУЗ из текста"),
    ("strip SUZ URLs", "удаление URL СУЗ"),
    ("internal thread", "отдельный поток внутренних сообщений"),
    ("JS-snippet + preview", "JS-фрагмент и предпросмотр"),
    ("offline-очередь", "очередь офлайн-сообщений"),
    # --- ASS / OCR / misc ---
    ("fine-tune prompts on dept history", "адаптация промптов на истории подразделения"),
    ("direct KB answer gate", "порог детерминированного ответа из KB"),
    ("citation-only mode", "режим ответа только с цитированием источника"),
    ("HITL overlay", "интерфейс ручной проверки (HITL) поверх распознанного"),
    ("few-shot / retrain", "дообучение few-shot"),
    ("blue/green publish without downtime", "публикация blue/green без простоя"),
    ("drag-drop scenario", "редактор сценария drag-and-drop"),
    ("sandbox run scenario", "прогон сценария в песочнице"),
    ("preview dialog", "предпросмотр диалога"),
    ("embedding match §5.2.3", "сопоставление по embedding §5.2.3"),
    ("single example enough", "достаточно одного примера"),
    ("dedup gate", "контроль дубликатов"),
    ("dedup §5.2.14", "дедупликация §5.2.14"),
    ("merge/ignore", "объединение / игнорирование"),
    ("content policy", "политика фильтрации контента"),
    ("content filter", "фильтр контента"),
    ("whitelist ИБ", "белый список, согласованный с ИБ"),
    ("whitelist §5.1.10", "белый список сценариев §5.1.10"),
    ("FeedbackEvent", "событие обратной связи (FeedbackEvent)"),
    ("source example", "исходный пример вопроса"),
    ("training set", "обучающая выборка"),
    ("training candidates", "кандидаты для обучения"),
    ("failed ASR samples", "неудачные образцы ASR"),
    ("concurrent users", "одновременные пользователи"),
    ("concurrent calls", "одновременные звонки"),
    ("each new client utterance", "каждая новая реплика клиента"),
    ("active call / chat in Hub", "активный звонок / чат в Hub"),
    ("client message webhook", "webhook сообщения клиента"),
    ("client blocked", "клиент заблокирован"),
    ("client disconnect", "отключение клиента"),
    ("block client action", "действие блокировки клиента"),
    ("supervisor canvas", "интерфейс супервизора (canvas)"),
    ("standalone sufer panel", "отдельная панель суфлёра"),
    ("standalone sufer panel", "отдельная панель суфлёра"),
    ("sufer in ARM right panel, not Hub tab", "суфлёр в правой панели АРМ, не во вкладке Hub"),
    ("intent change", "смена намерения"),
    ("intent classifier", "классификатор намерений"),
    ("intent routing", "маршрутизация по намерению"),
    ("low confidence", "низкая уверенность"),
    ("low score", "низкий score релевантности"),
    ("low relevance", "низкая релевантность"),
    ("chips вариантов", "кнопки-варианты (chips)"),
    ("chips / variants", "кнопки-варiанты / варианты ответа"),
    ("chips / handoff", "кнопки-варианты / передача оператору"),
    ("chips / escalate", "кнопки-варианты / эскалация"),
    ("analog", "аналог"),
    ("embedding match §5.2.3", "сопоставление по близости векторных представлений (embedding) §5.2.3"),
    ("Hub tab «Суфлёр» only", "вкладка Hub «Суфлёр» только для роли оператора телефонии"),
    ("author edits graph", "автор редактирует граф сценария"),
    ("Studio: branches, API hooks, no code", "Studio: ветвления, API-хуки, без программирования"),
    ("published scenario version", "опубликованная версия сценария"),
    ("hotfix scenario", "срочное исправление сценария"),
    ("live update", "обновление без перезапуска (live update)"),
    ("admin Studio", "администратор в Studio"),
    ("visual flow editor embed Hub", "визуальный редактор потока, встроенный в Hub"),
    ("version publish", "публикация версии"),
    ("semver + changelog", "семантическое версионирование (semver) и журнал изменений"),
    ("rollback available", "доступен откат версии"),
    ("import/export", "импорт / экспорт"),
    ("JSON scenario bundle", "JSON-пакет сценария"),
    ("migrate between envs", "перенос между средами (test/prod)"),
    ("edit draft", "редактирование черновика ответа"),
    ("log `sufler_text` vs `operator_sent`", "журналирование «текст суфлёра» vs «отправлено оператором»"),
    ("client msg without permalink", "сообщение клиенту без permalink СУЗ"),
    ("manual reply", "ручной ответ оператора"),
    ("client msg in chat", "сообщение клиента в чате"),
    ("same pair UI as phone; single «Вставить»", "тот же UI пар «реплика→подсказка», что в телефонии; одна кнопка «Вставить»"),
    ("compact ARM sufer", "компактная панель суфлёра в АРМ"),
    ("Hub module load", "загрузка модуля в Hub"),
    ("reuse platform LLM service", "использование общего сервиса LLM платформы"),
    ("assistant uses shared LLM", "ассистент использует общий LLM"),
    ("terminology / history", "терминология / история диалогов подразделения"),
    ("adapted tone", "адаптированный тон ответов"),
    ("any query", "любой запрос пользователя"),
    ("SLA p95 ≤2s response", "SLA: p95 времени ответа ≤2 с"),
    ("timely answer", "ответ в установленный SLA"),
    ("scale to 2000 sessions", "масштабирование до 2000 сессий"),
    ("no SLA breach", "без нарушения SLA"),
    ("paraphrase query", "перефразированный запрос"),
    ("duplicate question", "дубликат вопроса"),
    ("reject duplicate", "отклонение дубликата"),
    ("admin edits prompt", "администратор редактирует промпт"),
    ("CRUD without deploy §5.3.2.2", "CRUD без переразвёртывания §5.3.2.2"),
    ("published prompt", "опубликованный промпт"),
    ("semantic threshold", "порог семантической близости"),
    ("relevant chunks only", "только релевантные фрагменты контекста"),
    ("OCR module", "модуль OCR"),
    ("platform LLM for post-OCR tasks §6.1.1", "общий LLM платформы для постобработки OCR §6.1.1"),
    ("shared LLM layer", "общий слой LLM"),
    ("throughput", "требование к пропускной способности"),
    ("≥1 page/s/worker §6.1.19", "≥1 страница/с на воркер §6.1.19"),
    ("performance SLA", "SLA по производительности"),
    ("platform SLO", "целевые SLO платформы"),
    ("≤500 chars, 1–2s, ≥10 RPS §3.4", "≤500 символов, 1–2 с, ≥10 RPS §3.4"),
    ("met SLA on load test", "SLA выполнен по нагрузочному тесту"),
    ("load test §5.1.35", "нагрузочное тестирование §5.1.35"),
    ("admin test", "тестовый прогон администратором"),
    ("admin ASR settings", "настройки ASR администратором"),
    ("negative)", "негативный сценарий)"),
    (" negative.", " негативный сценарий."),
    ("regression", "регрессионное тестирование"),
    ("orchestration", "оркестрация (координация сервисов)"),
    ("orchestration tools", "оркестрация инструментов"),
    ("pipeline", "конвейер обработки"),
    ("без runtime HTTP к СУЗ", "без HTTP-обращений к СУЗ в режиме штатной эксплуатации (runtime)"),
    ("prompt и ответ на языке запроса", "промпт и ответ на языке запроса"),
    ("QU + history summary (FR-SUF-15) + RAG", "QU + сжатое резюме истории (FR-SUF-15) + RAG"),
    ("модуль QU embedded", "встроенный модуль QU"),
    ("config `min_relevance` per KB", "конфигурация `min_relevance` для каждой KB"),
    ("branch «уточняющие вопросы»", "ветка сценария «уточняющие вопросы»"),
    ("score < порога", "оценка релевантности ниже порога"),
    ("dual-leg recording", "двухканальная запись разговора"),
    ("speech stream", "непрерывный поток речи"),
    ("audio frame", "очередной фрейм аудиопотока"),
    ("export queue →", "очередь экспорта →"),
    ("UI просмотр для QA", "интерфейс просмотра для контроля качества (QA)"),
    ("INT-T audio lab", "INT-T: акустическая лаборатория"),
    ("ASS-T-18 (KB admin)", "ASS-T-18 (админ KB)"),
    ("metadata", "метаданные"),
    ("config ", "конфигурация "),
    ("preview ", "предпросмотр "),
    ("upload/", "загрузка /"),
    (" upload ", " загрузка "),
    ("import ", "импорт "),
    ("export ", "экспорт "),
    ("batch ", "пакетная обработка "),
    ("cluster ", "кластер "),
    ("sandbox ", "песочница "),
    ("cron ", "планировщик cron "),
    (" webhook", " webhook"),
]

# Expand short «Вход» fragments to fuller phrases.
_ENTRY_EXPAND: list[tuple[str, str]] = [
    ("вариант формулировки.", "новый или эталонный вариант формулировки вопроса в обучающей выборке KB."),
    ("любой запрос QU.", "любой запрос, поступающий в модуль понимания запросов (QU)."),
    ("новый вопрос пользователя.", "новый вопрос пользователя в диалоге или тестовом запросе."),
    ("поисковый запрос.", "поисковый запрос пользователя или администратора."),
    ("runtime суфлёра, ASR, RAG, LLM.", "штатная эксплуатация (runtime) суфлёра, ASR, RAG и LLM в контуре банка."),
    ("аудиопоток.", "аудиопоток активного звонка или тестовой записи."),
    ("audio frame.", "очередной фрейм аудиопотока."),
    ("speech stream.", "непрерывный поток речи."),
    ("активный звонок Oktell.", "активный звонок в Oktell с подключённым оператором."),
]


def localize(text: str) -> str:
    """Apply phrase replacements and light entry expansion."""
    out = text
    for old, new in _ENTRY_EXPAND:
        if out.startswith("**Вход:** " + old) or f"**Вход:** {old}" in out:
            out = out.replace(f"**Вход:** {old}", f"**Вход:** {new}", 1)
    for old, new in _PHRASES:
        if old in out:
            out = out.replace(old, new)
    # Residual English fragments in «Выход»
    out = re.sub(
        r"\bmatch\b",
        "семантическое совпадение",
        out,
        flags=re.I,
    )
    return out
